export interface CountryDialCodeOption {
  label: string;
  code: string;
}

export const countryDialCodeOptions: CountryDialCodeOption[] = [
  { label: "Afghanistan", code: "+93" },
  { label: "Albania", code: "+355" },
  { label: "Algeria", code: "+213" },
  { label: "Argentina", code: "+54" },
  { label: "Australia", code: "+61" },
  { label: "Austria", code: "+43" },
  { label: "Bahrain", code: "+973" },
  { label: "Bangladesh", code: "+880" },
  { label: "Belgium", code: "+32" },
  { label: "Botswana", code: "+267" },
  { label: "Brazil", code: "+55" },
  { label: "Bulgaria", code: "+359" },
  { label: "Canada", code: "+1" },
  { label: "China", code: "+86" },
  { label: "Cyprus", code: "+357" },
  { label: "Czech Republic", code: "+420" },
  { label: "Denmark", code: "+45" },
  { label: "Egypt", code: "+20" },
  { label: "Ethiopia", code: "+251" },
  { label: "Finland", code: "+358" },
  { label: "France", code: "+33" },
  { label: "Germany", code: "+49" },
  { label: "Ghana", code: "+233" },
  { label: "Greece", code: "+30" },
  { label: "Hong Kong", code: "+852" },
  { label: "Hungary", code: "+36" },
  { label: "India", code: "+91" },
  { label: "Indonesia", code: "+62" },
  { label: "Ireland", code: "+353" },
  { label: "Israel", code: "+972" },
  { label: "Italy", code: "+39" },
  { label: "Jamaica", code: "+1" },
  { label: "Japan", code: "+81" },
  { label: "Kenya", code: "+254" },
  { label: "Kuwait", code: "+965" },
  { label: "Malawi", code: "+265" },
  { label: "Malaysia", code: "+60" },
  { label: "Mauritius", code: "+230" },
  { label: "Mexico", code: "+52" },
  { label: "Morocco", code: "+212" },
  { label: "Mozambique", code: "+258" },
  { label: "Namibia", code: "+264" },
  { label: "Netherlands", code: "+31" },
  { label: "New Zealand", code: "+64" },
  { label: "Nigeria", code: "+234" },
  { label: "Norway", code: "+47" },
  { label: "Oman", code: "+968" },
  { label: "Pakistan", code: "+92" },
  { label: "Philippines", code: "+63" },
  { label: "Poland", code: "+48" },
  { label: "Portugal", code: "+351" },
  { label: "Qatar", code: "+974" },
  { label: "Romania", code: "+40" },
  { label: "Rwanda", code: "+250" },
  { label: "Saudi Arabia", code: "+966" },
  { label: "Serbia", code: "+381" },
  { label: "Singapore", code: "+65" },
  { label: "South Africa", code: "+27" },
  { label: "South Korea", code: "+82" },
  { label: "Spain", code: "+34" },
  { label: "Sri Lanka", code: "+94" },
  { label: "Sweden", code: "+46" },
  { label: "Switzerland", code: "+41" },
  { label: "Tanzania", code: "+255" },
  { label: "Thailand", code: "+66" },
  { label: "Turkey", code: "+90" },
  { label: "Uganda", code: "+256" },
  { label: "Ukraine", code: "+380" },
  { label: "United Arab Emirates", code: "+971" },
  { label: "United Kingdom", code: "+44" },
  { label: "United States", code: "+1" },
  { label: "Zambia", code: "+260" },
  { label: "Zimbabwe", code: "+263" },
];
